version: '3'
services:
  repairing-app:
    image: openjdk:17.0.1-jdk-slim
    env_file:
      - ./sendgrid.env
    ports:
      - "8080:8080"
    volumes:
      - ./target/RepairingApp-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - database

  frontend:
    build:
      context: ./src/main/frontend
    ports:
      - "5173:5173"
    depends_on:
      - repairing-app

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ASDasd:123
      MSSQL_PID: Express

    ports:
      - "1433:1433"
    volumes:
      - sql_server_data:/var/opt/mssql

volumes:
  sql_server_data: