version: '3'
services:
  repairing-app:
    image: openjdk:17.0.1-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./target/RepairingApp-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ASDasd:123
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sql_server_data:/var/opt/mssql

volumes:
  sql_server_data: